### ISSUE TITLE
Add ability to change bot prefix

### ISSUE THREAD

**Issue by LudusLight** [BrokenLamp/viav#77]
The current prefix is "-viav" - having the ability for server owners to change this would bring them more power over the bot in their guild.

Thank you Sentpa#0911 for bringing this to our attention

**Comment by BrandonDyer64** [comment]
Viav's prefix is `-viav `. It's long because it's both rarely used, and won't conflict with any other bot. If another bot complains about the `-` with something like `'viav' isn't a recognized command` then the other bot is misconfigured. No major bot will have this issue, including Groovy, which uses the `-` prefix. Allowing different discord servers to change the prefix invalidates the `Listening to -viav help` line below Viav's name.

Closing this for the reasons above.
